import {
  CFProfile,
  RatingPoint,
  PerformanceStats,
  VerdictCount,
  UpsolveProblem,
  TopicWeakness,
  Submission,
  ContestAutopsy,
} from "@/types";

export const MOCK_PROFILE: CFProfile = {
  handle: "Alex_Algo",
  rating: 1748,
  maxRating: 1824,
  rank: "Expert",
  maxRank: "Expert",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=faces",
  contribution: 14,
  lastSyncedAt: "12 minutes ago",
  globalRankEstimate: 6420,
};

export const MOCK_PERFORMANCE_STATS: PerformanceStats = {
  contestsCount: 38,
  solvedCount: 842,
  attemptedCount: 1120,
  successRate: 75.2,
  avgSolvedRating: 1510,
  upsolveRate: 64.8,
  bestRank: 312,
  avgRank: 1840,
  currentStreakDays: 12,
};

export const MOCK_RATING_HISTORY: RatingPoint[] = [
  { contestId: 901, contestName: "Codeforces Round 901 (Div. 2)", rating: 1320, oldRating: 1200, ratingChange: 120, rank: 2100, date: "Nov 2024", timestampSeconds: 1731000000 },
  { contestId: 905, contestName: "Codeforces Round 905 (Div. 3)", rating: 1412, oldRating: 1320, ratingChange: 92, rank: 980, date: "Dec 2024", timestampSeconds: 1733000000 },
  { contestId: 910, contestName: "Educational Codeforces Round 160", rating: 1465, oldRating: 1412, ratingChange: 53, rank: 2400, date: "Jan 2025", timestampSeconds: 1736000000 },
  { contestId: 914, contestName: "Codeforces Round 914 (Div. 2)", rating: 1420, oldRating: 1465, ratingChange: -45, rank: 4120, date: "Feb 2025", timestampSeconds: 1738000000 },
  { contestId: 918, contestName: "Codeforces Round 918 (Div. 4)", rating: 1530, oldRating: 1420, ratingChange: 110, rank: 450, date: "Mar 2025", timestampSeconds: 1740000000 },
  { contestId: 922, contestName: "Codeforces Round 922 (Div. 2)", rating: 1585, oldRating: 1530, ratingChange: 55, rank: 1850, date: "Apr 2025", timestampSeconds: 1743000000 },
  { contestId: 928, contestName: "Educational Codeforces Round 162", rating: 1640, oldRating: 1585, ratingChange: 55, rank: 1420, date: "May 2025", timestampSeconds: 1746000000 },
  { contestId: 934, contestName: "Codeforces Round 934 (Div. 2)", rating: 1610, oldRating: 1640, ratingChange: -30, rank: 3200, date: "Jun 2025", timestampSeconds: 1749000000 },
  { contestId: 940, contestName: "Codeforces Round 940 (Div. 2)", rating: 1695, oldRating: 1610, ratingChange: 85, rank: 890, date: "Jul 2025", timestampSeconds: 1752000000 },
  { contestId: 948, contestName: "Educational Codeforces Round 166", rating: 1740, oldRating: 1695, ratingChange: 45, rank: 1120, date: "Aug 2025", timestampSeconds: 1755000000 },
  { contestId: 955, contestName: "Codeforces Round 955 (Div. 2)", rating: 1824, oldRating: 1740, ratingChange: 84, rank: 312, date: "Sep 2025", timestampSeconds: 1758000000 },
  { contestId: 962, contestName: "Codeforces Round 962 (Div. 3)", rating: 1795, oldRating: 1824, ratingChange: -29, rank: 1540, date: "Oct 2025", timestampSeconds: 1760000000 },
  { contestId: 970, contestName: "Educational Codeforces Round 169", rating: 1748, oldRating: 1795, ratingChange: -47, rank: 2890, date: "Nov 2025", timestampSeconds: 1763000000 },
];

export const MOCK_VERDICT_COUNTS: VerdictCount[] = [
  { verdict: "Accepted", count: 842, percentage: 75.2, color: "#10b981" },
  { verdict: "Wrong Answer", count: 184, percentage: 16.4, color: "#f43f5e" },
  { verdict: "Time Limit Exceeded", count: 52, percentage: 4.6, color: "#f59e0b" },
  { verdict: "Runtime Error", count: 24, percentage: 2.1, color: "#a855f7" },
  { verdict: "Memory Limit Exceeded", count: 11, percentage: 1.0, color: "#0ea5e9" },
  { verdict: "Compilation Error", count: 7, percentage: 0.7, color: "#71717a" },
];

export const MOCK_UPSOLVE_PROBLEMS: UpsolveProblem[] = [
  {
    id: "970-D",
    contestId: 970,
    contestName: "Educational Codeforces Round 169",
    index: "D",
    name: "Colored Portals",
    rating: 1600,
    tags: ["binary search", "data structures", "graphs"],
    failedAttempts: 3,
    priority: "HIGH",
    reason: "Attempted 3 times during Round 169 with TLE. Target rating gap: only +12 from current rating.",
    url: "https://codeforces.com/contest/970/problem/D",
  },
  {
    id: "970-E",
    contestId: 970,
    contestName: "Educational Codeforces Round 169",
    index: "E",
    name: "Not a Nim Problem",
    rating: 1800,
    tags: ["games", "math", "number theory"],
    failedAttempts: 1,
    priority: "HIGH",
    reason: "Missed in final 15 minutes of contest. Involves prime factorization patterns you frequently encounter.",
    url: "https://codeforces.com/contest/970/problem/E",
  },
  {
    id: "962-E",
    contestId: 962,
    contestName: "Codeforces Round 962 (Div. 3)",
    index: "E",
    name: "Decode",
    rating: 1500,
    tags: ["combinatorics", "dp", "math"],
    failedAttempts: 2,
    priority: "MEDIUM",
    reason: "Failed on test 4 with WA. Prefix sum parity optimization required.",
    url: "https://codeforces.com/contest/962/problem/E",
  },
  {
    id: "955-D",
    contestId: 955,
    contestName: "Codeforces Round 955 (Div. 2)",
    index: "D",
    name: "Beauty of the mountains",
    rating: 1900,
    tags: ["2-sat", "math", "matrices", "number theory"],
    failedAttempts: 0,
    priority: "MEDIUM",
    reason: "Unattempted high-yield problem from your best contest. Excellent progression candidate.",
    url: "https://codeforces.com/contest/955/problem/D",
  },
];

export const MOCK_TOPIC_WEAKNESSES: TopicWeakness[] = [
  {
    tag: "dp",
    proficiencyScore: 42,
    weaknessScore: 68,
    solvedCount: 114,
    failedCount: 62,
    avgRating: 1540,
    status: "CRITICAL",
    actionRecommendation: "High failure rate on 1500-1700 DP (Knapsack & Bitmask). Prioritize DP fundamentals.",
  },
  {
    tag: "graphs",
    proficiencyScore: 78,
    weaknessScore: 24,
    solvedCount: 182,
    failedCount: 31,
    avgRating: 1680,
    status: "STRONG",
    actionRecommendation: "Excellent consistency on BFS/DFS and DSU. Ready for Shortest Paths & Flows.",
  },
  {
    tag: "binary search",
    proficiencyScore: 84,
    weaknessScore: 18,
    solvedCount: 95,
    failedCount: 14,
    avgRating: 1620,
    status: "STRONG",
    actionRecommendation: "Strong pattern recognition. Continue solving monotonic predicate problems.",
  },
  {
    tag: "data structures",
    proficiencyScore: 56,
    weaknessScore: 52,
    solvedCount: 88,
    failedCount: 42,
    avgRating: 1590,
    status: "NEEDS_WORK",
    actionRecommendation: "Occasional TLE on Segment Trees & Coordinate Compression. Review lazy propagation.",
  },
  {
    tag: "math",
    proficiencyScore: 69,
    weaknessScore: 35,
    solvedCount: 160,
    failedCount: 48,
    avgRating: 1550,
    status: "STABLE",
    actionRecommendation: "Solid combinatorics baseline. Work on modular inverse and sieve variations.",
  },
  {
    tag: "trees",
    proficiencyScore: 62,
    weaknessScore: 44,
    solvedCount: 74,
    failedCount: 29,
    avgRating: 1610,
    status: "STABLE",
    actionRecommendation: "Good on tree diameters and traversals. Needs work on Tree DP and LCA queries.",
  },
  {
    tag: "greedy",
    proficiencyScore: 81,
    weaknessScore: 21,
    solvedCount: 220,
    failedCount: 38,
    avgRating: 1490,
    status: "STRONG",
    actionRecommendation: "Very fast solve times on contest problems A and B.",
  },
  {
    tag: "strings",
    proficiencyScore: 36,
    weaknessScore: 74,
    solvedCount: 32,
    failedCount: 26,
    avgRating: 1520,
    status: "CRITICAL",
    actionRecommendation: "Severe deficiency in Hashing, KMP, and Tries. Recommended 3-day deep dive.",
  },
];

export const MOCK_RECENT_SUBMISSIONS: Submission[] = [
  {
    id: "278912340",
    problemIndex: "D",
    problemName: "Colored Portals",
    problemRating: 1600,
    contestId: 970,
    verdict: "TIME_LIMIT_EXCEEDED",
    language: "GNU C++20 (64)",
    runtimeMs: 2000,
    memoryKb: 38400,
    submittedAtSeconds: 1763004200,
    tags: ["binary search", "graphs"],
  },
  {
    id: "278910452",
    problemIndex: "C",
    problemName: "Splitting Items",
    problemRating: 1300,
    contestId: 970,
    verdict: "OK",
    language: "GNU C++20 (64)",
    runtimeMs: 140,
    memoryKb: 4200,
    submittedAtSeconds: 1763001800,
    tags: ["greedy", "sortings"],
  },
  {
    id: "278908120",
    problemIndex: "B",
    problemName: "Game with Doors",
    problemRating: 1100,
    contestId: 970,
    verdict: "OK",
    language: "GNU C++20 (64)",
    runtimeMs: 45,
    memoryKb: 1800,
    submittedAtSeconds: 1763000950,
    tags: ["implementation", "math"],
  },
  {
    id: "278905001",
    problemIndex: "A",
    problemName: "Closest Point",
    problemRating: 800,
    contestId: 970,
    verdict: "OK",
    language: "GNU C++20 (64)",
    runtimeMs: 31,
    memoryKb: 1200,
    submittedAtSeconds: 1763000210,
    tags: ["implementation"],
  },
  {
    id: "278850124",
    problemIndex: "E",
    problemName: "Decode",
    problemRating: 1500,
    contestId: 962,
    verdict: "WRONG_ANSWER",
    language: "GNU C++20 (64)",
    runtimeMs: 320,
    memoryKb: 12400,
    submittedAtSeconds: 1760005400,
    tags: ["dp", "math"],
  },
  {
    id: "278848123",
    problemIndex: "D",
    problemName: "Fun",
    problemRating: 1400,
    contestId: 962,
    verdict: "OK",
    language: "GNU C++20 (64)",
    runtimeMs: 210,
    memoryKb: 3400,
    submittedAtSeconds: 1760003200,
    tags: ["brute force", "math"],
  },
  {
    id: "278712390",
    problemIndex: "C",
    problemName: "Gorilla and the Exam",
    problemRating: 1200,
    contestId: 960,
    verdict: "OK",
    language: "GNU C++20 (64)",
    runtimeMs: 110,
    memoryKb: 2800,
    submittedAtSeconds: 1759002100,
    tags: ["greedy", "sortings"],
  },
];

export const MOCK_CONTEST_AUTOPSY: ContestAutopsy = {
  contestId: 970,
  contestName: "Educational Codeforces Round 169 (Rated for Div. 2)",
  date: "Nov 24, 2025",
  rank: 2890,
  ratingChange: -47,
  solvedProblems: ["A", "B", "C"],
  failedProblems: ["D"],
  missedProblems: ["E", "F"],
  insights: {
    wentWell: [
      "Solved Problem A in 3m 31s with zero penalty.",
      "Identified greedy interval logic on Problem B instantly.",
      "Clean implementation on Problem C with 0 wrong submissions.",
    ],
    wentWrong: [
      "Spent 68 minutes on Problem D debugging $O(N^2)$ approach before realizing it required $O(N \\log N)$ binary search on portals.",
      "Accumulated 3 TLE penalties on Problem D.",
      "Left zero time to inspect Problem E (1800), which was an accessible Nim variation.",
    ],
    actionItems: [
      "Upsolve Problem D immediately to lock in the 2-portal binary search pattern.",
      "Learn and drill the Grundy numbers / Nim Game theory for Problem E.",
      "Cap problem debugging at 25 minutes before reading subsequent problems.",
    ],
  },
};
