import {
  ContestDivision,
  VirtualContestProblem,
  VirtualParticipant,
} from "./types";

export interface PresetContestDefinition {
  id: number;
  title: string;
  division: ContestDivision;
  durationMinutes: number;
  problems: VirtualContestProblem[];
  botCompetitors: VirtualParticipant[];
}

export const PRESET_CONTESTS: PresetContestDefinition[] = [
  {
    id: 970,
    title: "Codeforces Round 970 (Div. 3)",
    division: "DIV3",
    durationMinutes: 135,
    problems: [
      {
        id: "970A",
        contestId: 970,
        index: "A",
        name: "Sakurako's Exam",
        rating: 800,
        tags: ["math", "greedy"],
        points: 500,
        solvedCount: 14200,
        expectedSolveMinutes: 6,
        statementSummary:
          "Sakurako has 'a' ones and 'b' twos. Can she divide them into two equal sums?",
        sampleInput: "3\n0 1\n1 1\n2 2",
        sampleOutput: "NO\nNO\nYES",
      },
      {
        id: "970B",
        contestId: 970,
        index: "B",
        name: "Square or Not",
        rating: 900,
        tags: ["geometry", "strings"],
        points: 1000,
        solvedCount: 11800,
        expectedSolveMinutes: 12,
        statementSummary:
          "Given a binary string of length N, determine whether it can represent a square binary matrix with 1s on borders and 0s inside.",
        sampleInput: "2\n4\n1111\n9\n111101111",
        sampleOutput: "Yes\nYes",
      },
      {
        id: "970C",
        contestId: 970,
        index: "C",
        name: "Longest Good Array",
        rating: 1000,
        tags: ["binary search", "math"],
        points: 1250,
        solvedCount: 9400,
        expectedSolveMinutes: 18,
        statementSummary:
          "An array is good if differences between consecutive elements are strictly increasing. Find max length of good array in [l, r].",
        sampleInput: "4\n1 3\n1 5\n10 20\n1 1",
        sampleOutput: "2\n3\n5\n1",
      },
      {
        id: "970D",
        contestId: 970,
        index: "D",
        name: "Sakurako's Hobby",
        rating: 1100,
        tags: ["dfs and similar", "dsu"],
        points: 1500,
        solvedCount: 7900,
        expectedSolveMinutes: 24,
        statementSummary:
          "Given a permutation and a binary color string, count how many black elements are reachable in the permutation cycle for each index.",
        sampleInput: "1\n5\n1 2 4 5 3\n10101",
        sampleOutput: "1 0 2 2 2",
      },
      {
        id: "970E",
        contestId: 970,
        index: "E",
        name: "Alternating String",
        rating: 1400,
        tags: ["greedy", "strings"],
        points: 2000,
        solvedCount: 4600,
        expectedSolveMinutes: 35,
        statementSummary:
          "Find min operations to make a string alternating (parity of even and odd positions have distinct characters). Delete at most one character if odd.",
        sampleInput: "3\n1\na\n2\ncb\n3\nabc",
        sampleOutput: "1\n0\n1",
      },
      {
        id: "970F",
        contestId: 970,
        index: "F",
        name: "Kosuke's Sloth",
        rating: 1600,
        tags: ["math", "number theory"],
        points: 2500,
        solvedCount: 2800,
        expectedSolveMinutes: 48,
        statementSummary:
          "Find the index of the n-th Fibonacci number divisible by k, modulo 1e9+7. Uses Pisano periods.",
        sampleInput: "2\n1 2\n3 2",
        sampleOutput: "3\n9",
      },
      {
        id: "970G",
        contestId: 970,
        index: "G",
        name: "Sakurako's Task",
        rating: 1700,
        tags: ["constructive algorithms", "math"],
        points: 2750,
        solvedCount: 1500,
        expectedSolveMinutes: 60,
        statementSummary:
          "Using operations a[i] = |a[i] - a[j]|, maximize the k-th missing non-negative integer.",
        sampleInput: "2\n2 1\n5 10\n3 3\n2 4 6",
        sampleOutput: "1\n7",
      },
      {
        id: "970H",
        contestId: 970,
        index: "H",
        name: "Sakurako's Box",
        rating: 1900,
        tags: ["data structures", "probabilities"],
        points: 3000,
        solvedCount: 890,
        expectedSolveMinutes: 75,
        statementSummary:
          "Compute expected value of a[i] * a[j] for randomly picked distinct i and j modulo 1e9+7.",
        sampleInput: "1\n3\n3 2 3",
        sampleOutput: "7",
      },
    ],
    botCompetitors: [
      {
        id: "bot-jiangly",
        handle: "jiangly",
        isUser: false,
        rank: 1,
        rating: 3750,
        avatar: "https://userpic.codeforces.org/no-title.jpg",
        solvedCount: 8,
        totalPoints: 12500,
        totalPenaltyMinutes: 285,
        results: {
          A: { problemIndex: "A", isSolved: true, solveTimeMinutes: 4, rejectedAttempts: 0, points: 492, icpcPenaltyMinutes: 4 },
          B: { problemIndex: "B", isSolved: true, solveTimeMinutes: 9, rejectedAttempts: 0, points: 964, icpcPenaltyMinutes: 9 },
          C: { problemIndex: "C", isSolved: true, solveTimeMinutes: 16, rejectedAttempts: 0, points: 1184, icpcPenaltyMinutes: 16 },
          D: { problemIndex: "D", isSolved: true, solveTimeMinutes: 23, rejectedAttempts: 0, points: 1408, icpcPenaltyMinutes: 23 },
          E: { problemIndex: "E", isSolved: true, solveTimeMinutes: 38, rejectedAttempts: 0, points: 1848, icpcPenaltyMinutes: 38 },
          F: { problemIndex: "F", isSolved: true, solveTimeMinutes: 52, rejectedAttempts: 0, points: 2240, icpcPenaltyMinutes: 52 },
          G: { problemIndex: "G", isSolved: true, solveTimeMinutes: 67, rejectedAttempts: 0, points: 2415, icpcPenaltyMinutes: 67 },
          H: { problemIndex: "H", isSolved: true, solveTimeMinutes: 76, rejectedAttempts: 0, points: 2620, icpcPenaltyMinutes: 76 },
        },
        botSchedule: [
          { problemIndex: "A", solveElapsedSeconds: 240, failedAttemptsBeforeAc: 0 },
          { problemIndex: "B", solveElapsedSeconds: 540, failedAttemptsBeforeAc: 0 },
          { problemIndex: "C", solveElapsedSeconds: 960, failedAttemptsBeforeAc: 0 },
          { problemIndex: "D", solveElapsedSeconds: 1380, failedAttemptsBeforeAc: 0 },
          { problemIndex: "E", solveElapsedSeconds: 2280, failedAttemptsBeforeAc: 0 },
          { problemIndex: "F", solveElapsedSeconds: 3120, failedAttemptsBeforeAc: 0 },
          { problemIndex: "G", solveElapsedSeconds: 4020, failedAttemptsBeforeAc: 0 },
          { problemIndex: "H", solveElapsedSeconds: 4560, failedAttemptsBeforeAc: 0 },
        ],
      },
      {
        id: "bot-radewoosh",
        handle: "Radewoosh",
        isUser: false,
        rank: 2,
        rating: 2950,
        avatar: "https://userpic.codeforces.org/no-title.jpg",
        solvedCount: 7,
        totalPoints: 9800,
        totalPenaltyMinutes: 320,
        results: {
          A: { problemIndex: "A", isSolved: true, solveTimeMinutes: 5, rejectedAttempts: 0, points: 490, icpcPenaltyMinutes: 5 },
          B: { problemIndex: "B", isSolved: true, solveTimeMinutes: 11, rejectedAttempts: 0, points: 956, icpcPenaltyMinutes: 11 },
          C: { problemIndex: "C", isSolved: true, solveTimeMinutes: 21, rejectedAttempts: 0, points: 1145, icpcPenaltyMinutes: 21 },
          D: { problemIndex: "D", isSolved: true, solveTimeMinutes: 31, rejectedAttempts: 1, points: 1326, icpcPenaltyMinutes: 51 },
          E: { problemIndex: "E", isSolved: true, solveTimeMinutes: 48, rejectedAttempts: 0, points: 1808, icpcPenaltyMinutes: 48 },
          F: { problemIndex: "F", isSolved: true, solveTimeMinutes: 72, rejectedAttempts: 0, points: 2080, icpcPenaltyMinutes: 72 },
          G: { problemIndex: "G", isSolved: true, solveTimeMinutes: 92, rejectedAttempts: 1, points: 2165, icpcPenaltyMinutes: 112 },
          H: { problemIndex: "H", isSolved: false, solveTimeMinutes: null, rejectedAttempts: 2, points: 0, icpcPenaltyMinutes: 0 },
        },
        botSchedule: [
          { problemIndex: "A", solveElapsedSeconds: 300, failedAttemptsBeforeAc: 0 },
          { problemIndex: "B", solveElapsedSeconds: 660, failedAttemptsBeforeAc: 0 },
          { problemIndex: "C", solveElapsedSeconds: 1260, failedAttemptsBeforeAc: 0 },
          { problemIndex: "D", solveElapsedSeconds: 1860, failedAttemptsBeforeAc: 1 },
          { problemIndex: "E", solveElapsedSeconds: 2880, failedAttemptsBeforeAc: 0 },
          { problemIndex: "F", solveElapsedSeconds: 4320, failedAttemptsBeforeAc: 0 },
          { problemIndex: "G", solveElapsedSeconds: 5520, failedAttemptsBeforeAc: 1 },
        ],
      },
      {
        id: "bot-errichto",
        handle: "Errichto",
        isUser: false,
        rank: 3,
        rating: 2600,
        avatar: "https://userpic.codeforces.org/no-title.jpg",
        solvedCount: 6,
        totalPoints: 7100,
        totalPenaltyMinutes: 290,
        results: {
          A: { problemIndex: "A", isSolved: true, solveTimeMinutes: 7, rejectedAttempts: 0, points: 486, icpcPenaltyMinutes: 7 },
          B: { problemIndex: "B", isSolved: true, solveTimeMinutes: 15, rejectedAttempts: 0, points: 940, icpcPenaltyMinutes: 15 },
          C: { problemIndex: "C", isSolved: true, solveTimeMinutes: 26, rejectedAttempts: 0, points: 1120, icpcPenaltyMinutes: 26 },
          D: { problemIndex: "D", isSolved: true, solveTimeMinutes: 38, rejectedAttempts: 0, points: 1348, icpcPenaltyMinutes: 38 },
          E: { problemIndex: "E", isSolved: true, solveTimeMinutes: 59, rejectedAttempts: 1, points: 1714, icpcPenaltyMinutes: 79 },
          F: { problemIndex: "F", isSolved: true, solveTimeMinutes: 85, rejectedAttempts: 2, points: 1880, icpcPenaltyMinutes: 125 },
          G: { problemIndex: "G", isSolved: false, solveTimeMinutes: null, rejectedAttempts: 1, points: 0, icpcPenaltyMinutes: 0 },
          H: { problemIndex: "H", isSolved: false, solveTimeMinutes: null, rejectedAttempts: 0, points: 0, icpcPenaltyMinutes: 0 },
        },
        botSchedule: [
          { problemIndex: "A", solveElapsedSeconds: 420, failedAttemptsBeforeAc: 0 },
          { problemIndex: "B", solveElapsedSeconds: 900, failedAttemptsBeforeAc: 0 },
          { problemIndex: "C", solveElapsedSeconds: 1560, failedAttemptsBeforeAc: 0 },
          { problemIndex: "D", solveElapsedSeconds: 2280, failedAttemptsBeforeAc: 0 },
          { problemIndex: "E", solveElapsedSeconds: 3540, failedAttemptsBeforeAc: 1 },
          { problemIndex: "F", solveElapsedSeconds: 5100, failedAttemptsBeforeAc: 2 },
        ],
      },
      {
        id: "bot-byteninja",
        handle: "ByteNinja",
        isUser: false,
        rank: 4,
        rating: 1650,
        avatar: "https://userpic.codeforces.org/no-title.jpg",
        solvedCount: 5,
        totalPoints: 5200,
        totalPenaltyMinutes: 245,
        results: {
          A: { problemIndex: "A", isSolved: true, solveTimeMinutes: 8, rejectedAttempts: 0, points: 484, icpcPenaltyMinutes: 8 },
          B: { problemIndex: "B", isSolved: true, solveTimeMinutes: 19, rejectedAttempts: 0, points: 924, icpcPenaltyMinutes: 19 },
          C: { problemIndex: "C", isSolved: true, solveTimeMinutes: 34, rejectedAttempts: 1, points: 1064, icpcPenaltyMinutes: 54 },
          D: { problemIndex: "D", isSolved: true, solveTimeMinutes: 47, rejectedAttempts: 0, points: 1312, icpcPenaltyMinutes: 47 },
          E: { problemIndex: "E", isSolved: true, solveTimeMinutes: 77, rejectedAttempts: 2, points: 1592, icpcPenaltyMinutes: 117 },
          F: { problemIndex: "F", isSolved: false, solveTimeMinutes: null, rejectedAttempts: 2, points: 0, icpcPenaltyMinutes: 0 },
          G: { problemIndex: "G", isSolved: false, solveTimeMinutes: null, rejectedAttempts: 0, points: 0, icpcPenaltyMinutes: 0 },
          H: { problemIndex: "H", isSolved: false, solveTimeMinutes: null, rejectedAttempts: 0, points: 0, icpcPenaltyMinutes: 0 },
        },
        botSchedule: [
          { problemIndex: "A", solveElapsedSeconds: 480, failedAttemptsBeforeAc: 0 },
          { problemIndex: "B", solveElapsedSeconds: 1140, failedAttemptsBeforeAc: 0 },
          { problemIndex: "C", solveElapsedSeconds: 2040, failedAttemptsBeforeAc: 1 },
          { problemIndex: "D", solveElapsedSeconds: 2820, failedAttemptsBeforeAc: 0 },
          { problemIndex: "E", solveElapsedSeconds: 4620, failedAttemptsBeforeAc: 2 },
        ],
      },
      {
        id: "bot-codemaster99",
        handle: "CodeMaster99",
        isUser: false,
        rank: 5,
        rating: 1480,
        avatar: "https://userpic.codeforces.org/no-title.jpg",
        solvedCount: 4,
        totalPoints: 3450,
        totalPenaltyMinutes: 150,
        results: {
          A: { problemIndex: "A", isSolved: true, solveTimeMinutes: 12, rejectedAttempts: 0, points: 476, icpcPenaltyMinutes: 12 },
          B: { problemIndex: "B", isSolved: true, solveTimeMinutes: 24, rejectedAttempts: 1, points: 884, icpcPenaltyMinutes: 44 },
          C: { problemIndex: "C", isSolved: true, solveTimeMinutes: 42, rejectedAttempts: 0, points: 1040, icpcPenaltyMinutes: 42 },
          D: { problemIndex: "D", isSolved: true, solveTimeMinutes: 52, rejectedAttempts: 0, points: 1292, icpcPenaltyMinutes: 52 },
          E: { problemIndex: "E", isSolved: false, solveTimeMinutes: null, rejectedAttempts: 3, points: 0, icpcPenaltyMinutes: 0 },
          F: { problemIndex: "F", isSolved: false, solveTimeMinutes: null, rejectedAttempts: 0, points: 0, icpcPenaltyMinutes: 0 },
          G: { problemIndex: "G", isSolved: false, solveTimeMinutes: null, rejectedAttempts: 0, points: 0, icpcPenaltyMinutes: 0 },
          H: { problemIndex: "H", isSolved: false, solveTimeMinutes: null, rejectedAttempts: 0, points: 0, icpcPenaltyMinutes: 0 },
        },
        botSchedule: [
          { problemIndex: "A", solveElapsedSeconds: 720, failedAttemptsBeforeAc: 0 },
          { problemIndex: "B", solveElapsedSeconds: 1440, failedAttemptsBeforeAc: 1 },
          { problemIndex: "C", solveElapsedSeconds: 2520, failedAttemptsBeforeAc: 0 },
          { problemIndex: "D", solveElapsedSeconds: 3120, failedAttemptsBeforeAc: 0 },
        ],
      },
      {
        id: "bot-algonovice",
        handle: "AlgoNovice",
        isUser: false,
        rank: 6,
        rating: 1250,
        avatar: "https://userpic.codeforces.org/no-title.jpg",
        solvedCount: 2,
        totalPoints: 1280,
        totalPenaltyMinutes: 65,
        results: {
          A: { problemIndex: "A", isSolved: true, solveTimeMinutes: 15, rejectedAttempts: 1, points: 420, icpcPenaltyMinutes: 35 },
          B: { problemIndex: "B", isSolved: true, solveTimeMinutes: 30, rejectedAttempts: 0, points: 880, icpcPenaltyMinutes: 30 },
          C: { problemIndex: "C", isSolved: false, solveTimeMinutes: null, rejectedAttempts: 2, points: 0, icpcPenaltyMinutes: 0 },
          D: { problemIndex: "D", isSolved: false, solveTimeMinutes: null, rejectedAttempts: 1, points: 0, icpcPenaltyMinutes: 0 },
          E: { problemIndex: "E", isSolved: false, solveTimeMinutes: null, rejectedAttempts: 0, points: 0, icpcPenaltyMinutes: 0 },
          F: { problemIndex: "F", isSolved: false, solveTimeMinutes: null, rejectedAttempts: 0, points: 0, icpcPenaltyMinutes: 0 },
          G: { problemIndex: "G", isSolved: false, solveTimeMinutes: null, rejectedAttempts: 0, points: 0, icpcPenaltyMinutes: 0 },
          H: { problemIndex: "H", isSolved: false, solveTimeMinutes: null, rejectedAttempts: 0, points: 0, icpcPenaltyMinutes: 0 },
        },
        botSchedule: [
          { problemIndex: "A", solveElapsedSeconds: 900, failedAttemptsBeforeAc: 1 },
          { problemIndex: "B", solveElapsedSeconds: 1800, failedAttemptsBeforeAc: 0 },
        ],
      },
    ],
  },
  {
    id: 965,
    title: "Codeforces Round 965 (Div. 2)",
    division: "DIV2",
    durationMinutes: 120,
    problems: [
      {
        id: "965A",
        contestId: 965,
        index: "A",
        name: "Find K Distinct Points with Fixed Center",
        rating: 800,
        tags: ["constructive algorithms", "geometry"],
        points: 500,
        solvedCount: 16500,
        expectedSolveMinutes: 7,
        statementSummary:
          "Given integers xc, yc and k, find k distinct points on a plane such that their center of mass is (xc, yc).",
        sampleInput: "2\n0 0 1\n1 10 2",
        sampleOutput: "0 0\n0 10\n2 10",
      },
      {
        id: "965B",
        contestId: 965,
        index: "B",
        name: "Minimize Equal Psum",
        rating: 1000,
        tags: ["constructive algorithms"],
        points: 1000,
        solvedCount: 12300,
        expectedSolveMinutes: 15,
        statementSummary:
          "Given a permutation p, construct a permutation q such that the count of subsegment sums sum(p[l..r]) == sum(q[l..r]) is minimized.",
        sampleInput: "2\n2\n1 2\n3\n2 3 1",
        sampleOutput: "2 1\n3 1 2",
      },
      {
        id: "965C",
        contestId: 965,
        index: "C",
        name: "Perform Operations to Maximize Score",
        rating: 1400,
        tags: ["binary search", "greedy", "sortings"],
        points: 1500,
        solvedCount: 5400,
        expectedSolveMinutes: 32,
        statementSummary:
          "Given array 'a' and binary array 'b' (where operations can be applied), find max possible score a[i] + median(a \\ {a[i]}).",
        sampleInput: "1\n4 4\n1 2 3 4\n0 1 0 1",
        sampleOutput: "9",
      },
      {
        id: "965D",
        contestId: 965,
        index: "D",
        name: "Determine Winning Islands in Race",
        rating: 1700,
        tags: ["data structures", "dp", "graphs", "greedy"],
        points: 2000,
        solvedCount: 2200,
        expectedSolveMinutes: 45,
        statementSummary:
          "In a directed acyclic bridge network, determine for each starting island s whether Elsie can beat Bessie to island n.",
        sampleInput: "1\n4 2\n1 3\n2 4",
        sampleOutput: "110",
      },
      {
        id: "965E",
        contestId: 965,
        index: "E",
        name: "Eliminating Balls With Merging",
        rating: 2100,
        tags: ["binary search", "dsu", "trees"],
        points: 2500,
        solvedCount: 950,
        expectedSolveMinutes: 60,
        statementSummary:
          "Adjacent balls merge by absorbing the smaller into the larger. Count how many initial balls can become the final sole survivor.",
        sampleInput: "1\n5\n3 2 4 1 5",
        sampleOutput: "3",
      },
    ],
    botCompetitors: [
      {
        id: "bot-tourist",
        handle: "tourist",
        isUser: false,
        rank: 1,
        rating: 3850,
        avatar: "https://userpic.codeforces.org/no-title.jpg",
        solvedCount: 5,
        totalPoints: 7200,
        totalPenaltyMinutes: 110,
        results: {
          A: { problemIndex: "A", isSolved: true, solveTimeMinutes: 3, rejectedAttempts: 0, points: 494, icpcPenaltyMinutes: 3 },
          B: { problemIndex: "B", isSolved: true, solveTimeMinutes: 7, rejectedAttempts: 0, points: 972, icpcPenaltyMinutes: 7 },
          C: { problemIndex: "C", isSolved: true, solveTimeMinutes: 20, rejectedAttempts: 0, points: 1420, icpcPenaltyMinutes: 20 },
          D: { problemIndex: "D", isSolved: true, solveTimeMinutes: 35, rejectedAttempts: 0, points: 1860, icpcPenaltyMinutes: 35 },
          E: { problemIndex: "E", isSolved: true, solveTimeMinutes: 45, rejectedAttempts: 0, points: 2450, icpcPenaltyMinutes: 45 },
        },
        botSchedule: [
          { problemIndex: "A", solveElapsedSeconds: 180, failedAttemptsBeforeAc: 0 },
          { problemIndex: "B", solveElapsedSeconds: 420, failedAttemptsBeforeAc: 0 },
          { problemIndex: "C", solveElapsedSeconds: 1200, failedAttemptsBeforeAc: 0 },
          { problemIndex: "D", solveElapsedSeconds: 2100, failedAttemptsBeforeAc: 0 },
          { problemIndex: "E", solveElapsedSeconds: 2700, failedAttemptsBeforeAc: 0 },
        ],
      },
      {
        id: "bot-petr",
        handle: "Petr",
        isUser: false,
        rank: 2,
        rating: 2900,
        avatar: "https://userpic.codeforces.org/no-title.jpg",
        solvedCount: 4,
        totalPoints: 4800,
        totalPenaltyMinutes: 130,
        results: {
          A: { problemIndex: "A", isSolved: true, solveTimeMinutes: 6, rejectedAttempts: 0, points: 488, icpcPenaltyMinutes: 6 },
          B: { problemIndex: "B", isSolved: true, solveTimeMinutes: 14, rejectedAttempts: 0, points: 944, icpcPenaltyMinutes: 14 },
          C: { problemIndex: "C", isSolved: true, solveTimeMinutes: 36, rejectedAttempts: 1, points: 1306, icpcPenaltyMinutes: 56 },
          D: { problemIndex: "D", isSolved: true, solveTimeMinutes: 54, rejectedAttempts: 0, points: 1784, icpcPenaltyMinutes: 54 },
          E: { problemIndex: "E", isSolved: false, solveTimeMinutes: null, rejectedAttempts: 2, points: 0, icpcPenaltyMinutes: 0 },
        },
        botSchedule: [
          { problemIndex: "A", solveElapsedSeconds: 360, failedAttemptsBeforeAc: 0 },
          { problemIndex: "B", solveElapsedSeconds: 840, failedAttemptsBeforeAc: 0 },
          { problemIndex: "C", solveElapsedSeconds: 2160, failedAttemptsBeforeAc: 1 },
          { problemIndex: "D", solveElapsedSeconds: 3240, failedAttemptsBeforeAc: 0 },
        ],
      },
    ],
  },
];
